//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodByMe.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodByMe.Core.Resources.Text", typeof(Text).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more.
        /// </summary>
        public static string AddIngredientButton {
            get {
                return ResourceManager.GetString("AddIngredientButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add step.
        /// </summary>
        public static string AddStepButton {
            get {
                return ResourceManager.GetString("AddStepButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Recipes.
        /// </summary>
        public static string AllRecipesLabel {
            get {
                return ResourceManager.GetString("AllRecipesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesLabel {
            get {
                return ResourceManager.GetString("CategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking steps.
        /// </summary>
        public static string CookingStepsLabel {
            get {
                return ResourceManager.GetString("CookingStepsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking time.
        /// </summary>
        public static string CookingTimeLabel {
            get {
                return ResourceManager.GetString("CookingTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string FavoritesLabel {
            get {
                return ResourceManager.GetString("FavoritesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string HoursShort {
            get {
                return ResourceManager.GetString("HoursShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient.
        /// </summary>
        public static string IngredientLabel {
            get {
                return ResourceManager.GetString("IngredientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string IngredientsLabel {
            get {
                return ResourceManager.GetString("IngredientsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string MinutesShort {
            get {
                return ResourceManager.GetString("MinutesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My recipe.
        /// </summary>
        public static string NewRecipeTitle {
            get {
                return ResourceManager.GetString("NewRecipeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the pencil to add cooking steps.
        /// </summary>
        public static string NoCookingStepsText {
            get {
                return ResourceManager.GetString("NoCookingStepsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the pencil to add ingredients.
        /// </summary>
        public static string NoIngredientsText {
            get {
                return ResourceManager.GetString("NoIngredientsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no recipes here yet. Press the button to add one.
        /// </summary>
        public static string NoRecipesText {
            get {
                return ResourceManager.GetString("NoRecipesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a photo.
        /// </summary>
        public static string PickPhoto {
            get {
                return ResourceManager.GetString("PickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a photo.
        /// </summary>
        public static string PickPhotoCamera {
            get {
                return ResourceManager.GetString("PickPhotoCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an image.
        /// </summary>
        public static string PickPhotoGallery {
            get {
                return ResourceManager.GetString("PickPhotoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string QuantityLabel {
            get {
                return ResourceManager.GetString("QuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe name.
        /// </summary>
        public static string RecipeNameLabel {
            get {
                return ResourceManager.GetString("RecipeNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appetizers.
        /// </summary>
        public static string ReferenceCategoryAppetizers {
            get {
                return ResourceManager.GetString("ReferenceCategoryAppetizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baking.
        /// </summary>
        public static string ReferenceCategoryBaking {
            get {
                return ResourceManager.GetString("ReferenceCategoryBaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desserts.
        /// </summary>
        public static string ReferenceCategoryDesserts {
            get {
                return ResourceManager.GetString("ReferenceCategoryDesserts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        public static string ReferenceCategoryDinner {
            get {
                return ResourceManager.GetString("ReferenceCategoryDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks.
        /// </summary>
        public static string ReferenceCategoryDrinks {
            get {
                return ResourceManager.GetString("ReferenceCategoryDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string ReferenceCategoryOther {
            get {
                return ResourceManager.GetString("ReferenceCategoryOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salads.
        /// </summary>
        public static string ReferenceCategorySalads {
            get {
                return ResourceManager.GetString("ReferenceCategorySalads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cups.
        /// </summary>
        public static string ReferenceMeasureCup {
            get {
                return ResourceManager.GetString("ReferenceMeasureCup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cups.
        /// </summary>
        public static string ReferenceMeasureCupShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureCupShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gram.
        /// </summary>
        public static string ReferenceMeasureGram {
            get {
                return ResourceManager.GetString("ReferenceMeasureGram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        public static string ReferenceMeasureGramShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureGramShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilogramm.
        /// </summary>
        public static string ReferenceMeasureKilogram {
            get {
                return ResourceManager.GetString("ReferenceMeasureKilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        public static string ReferenceMeasureKilogramShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureKilogramShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liter.
        /// </summary>
        public static string ReferenceMeasureLiter {
            get {
                return ResourceManager.GetString("ReferenceMeasureLiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l.
        /// </summary>
        public static string ReferenceMeasureLiterShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureLiterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milligram.
        /// </summary>
        public static string ReferenceMeasureMilligram {
            get {
                return ResourceManager.GetString("ReferenceMeasureMilligram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg.
        /// </summary>
        public static string ReferenceMeasureMilligramShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureMilligramShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliliter.
        /// </summary>
        public static string ReferenceMeasureMilliliter {
            get {
                return ResourceManager.GetString("ReferenceMeasureMilliliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        public static string ReferenceMeasureMilliliterShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureMilliliterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to piece.
        /// </summary>
        public static string ReferenceMeasurePiece {
            get {
                return ResourceManager.GetString("ReferenceMeasurePiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pcs.
        /// </summary>
        public static string ReferenceMeasurePieceShort {
            get {
                return ResourceManager.GetString("ReferenceMeasurePieceShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pinch.
        /// </summary>
        public static string ReferenceMeasurePinch {
            get {
                return ResourceManager.GetString("ReferenceMeasurePinch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pinch.
        /// </summary>
        public static string ReferenceMeasurePinchShort {
            get {
                return ResourceManager.GetString("ReferenceMeasurePinchShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to table spoon.
        /// </summary>
        public static string ReferenceMeasureTableSpoon {
            get {
                return ResourceManager.GetString("ReferenceMeasureTableSpoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbsp.
        /// </summary>
        public static string ReferenceMeasureTableSpoonShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureTableSpoonShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by taste.
        /// </summary>
        public static string ReferenceMeasureTaste {
            get {
                return ResourceManager.GetString("ReferenceMeasureTaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taste.
        /// </summary>
        public static string ReferenceMeasureTasteShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureTasteShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tea spoon.
        /// </summary>
        public static string ReferenceMeasureTeaSpoon {
            get {
                return ResourceManager.GetString("ReferenceMeasureTeaSpoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tsp.
        /// </summary>
        public static string ReferenceMeasureTeaSpoonShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureTeaSpoonShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step #.
        /// </summary>
        public static string StepNo {
            get {
                return ResourceManager.GetString("StepNo", resourceCulture);
            }
        }
    }
}
