//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodByMe.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodByMe.Core.Resources.Text", typeof(Text).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more.
        /// </summary>
        internal static string AddIngredientButton {
            get {
                return ResourceManager.GetString("AddIngredientButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add step.
        /// </summary>
        internal static string AddStepButton {
            get {
                return ResourceManager.GetString("AddStepButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking steps.
        /// </summary>
        internal static string CookingStepsLabel {
            get {
                return ResourceManager.GetString("CookingStepsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking time.
        /// </summary>
        internal static string CookingTimeLabel {
            get {
                return ResourceManager.GetString("CookingTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient.
        /// </summary>
        internal static string IngredientLabel {
            get {
                return ResourceManager.GetString("IngredientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        internal static string IngredientsLabel {
            get {
                return ResourceManager.GetString("IngredientsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string QuantityLabel {
            get {
                return ResourceManager.GetString("QuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe name.
        /// </summary>
        internal static string RecipeNameLabel {
            get {
                return ResourceManager.GetString("RecipeNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appetizers.
        /// </summary>
        internal static string ReferenceCategoryAppetizers {
            get {
                return ResourceManager.GetString("ReferenceCategoryAppetizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desserts.
        /// </summary>
        internal static string ReferenceCategoryDesserts {
            get {
                return ResourceManager.GetString("ReferenceCategoryDesserts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        internal static string ReferenceCategoryDinner {
            get {
                return ResourceManager.GetString("ReferenceCategoryDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks.
        /// </summary>
        internal static string ReferenceCategoryDrinks {
            get {
                return ResourceManager.GetString("ReferenceCategoryDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string ReferenceCategoryOther {
            get {
                return ResourceManager.GetString("ReferenceCategoryOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salads.
        /// </summary>
        internal static string ReferenceCategorySalads {
            get {
                return ResourceManager.GetString("ReferenceCategorySalads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cups.
        /// </summary>
        internal static string ReferenceMeasureCup {
            get {
                return ResourceManager.GetString("ReferenceMeasureCup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cups.
        /// </summary>
        internal static string ReferenceMeasureCupShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureCupShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gram.
        /// </summary>
        internal static string ReferenceMeasureGram {
            get {
                return ResourceManager.GetString("ReferenceMeasureGram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        internal static string ReferenceMeasureGramShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureGramShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilogramm.
        /// </summary>
        internal static string ReferenceMeasureKilogram {
            get {
                return ResourceManager.GetString("ReferenceMeasureKilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        internal static string ReferenceMeasureKilogramShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureKilogramShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liter.
        /// </summary>
        internal static string ReferenceMeasureLiter {
            get {
                return ResourceManager.GetString("ReferenceMeasureLiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l.
        /// </summary>
        internal static string ReferenceMeasureLiterShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureLiterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milligram.
        /// </summary>
        internal static string ReferenceMeasureMilligram {
            get {
                return ResourceManager.GetString("ReferenceMeasureMilligram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg.
        /// </summary>
        internal static string ReferenceMeasureMilligramShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureMilligramShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliliter.
        /// </summary>
        internal static string ReferenceMeasureMilliliter {
            get {
                return ResourceManager.GetString("ReferenceMeasureMilliliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        internal static string ReferenceMeasureMilliliterShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureMilliliterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to piece.
        /// </summary>
        internal static string ReferenceMeasurePiece {
            get {
                return ResourceManager.GetString("ReferenceMeasurePiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pcs.
        /// </summary>
        internal static string ReferenceMeasurePieceShort {
            get {
                return ResourceManager.GetString("ReferenceMeasurePieceShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pinch.
        /// </summary>
        internal static string ReferenceMeasurePinch {
            get {
                return ResourceManager.GetString("ReferenceMeasurePinch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pinch.
        /// </summary>
        internal static string ReferenceMeasurePinchShort {
            get {
                return ResourceManager.GetString("ReferenceMeasurePinchShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to table spoon.
        /// </summary>
        internal static string ReferenceMeasureTableSpoon {
            get {
                return ResourceManager.GetString("ReferenceMeasureTableSpoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbsp.
        /// </summary>
        internal static string ReferenceMeasureTableSpoonShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureTableSpoonShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by taste.
        /// </summary>
        internal static string ReferenceMeasureTaste {
            get {
                return ResourceManager.GetString("ReferenceMeasureTaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taste.
        /// </summary>
        internal static string ReferenceMeasureTasteShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureTasteShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tea spoon.
        /// </summary>
        internal static string ReferenceMeasureTeaSpoon {
            get {
                return ResourceManager.GetString("ReferenceMeasureTeaSpoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tsp.
        /// </summary>
        internal static string ReferenceMeasureTeaSpoonShort {
            get {
                return ResourceManager.GetString("ReferenceMeasureTeaSpoonShort", resourceCulture);
            }
        }
    }
}
